### PR TITLE
Added @with_kw + parametric types

### PR DESCRIPTION
**Pull request by csimal**
I've done the changes suggested in #27, namely

- Added Parameters.jl to the list of dependencies
- modified the definitions of `Clock`, `TICK`, `SLEEP_SEC`, `XYZ`, `ECS`, `ECSIteratorState`, `PhysicsObjectInfo` and `Physics` to use `@with_kw` and be parametric types.

I've done my best to minimize the changes in the code, but making the types parametric is likely to be a breaking change, which I can't test since tests are broken #25.
In particular, some datatypes like `XYZ` can now only have all fields of the same type, which may cause some surprises when trying to create instances like
```julia
XYZ(1,1.0,0) # undefined
XYZ(x=1.0) # undefined
XYZ{Float64}(x=1.0) # the correct version of the previous line
```

So yeah, this needs to be reviewed and tested, and possibly modified to reflect developer intent.

### CODE REVIEW

**Comment by jhigginbotham64** [comment]
Unfortunately I can't test changes either because my dev environment is still borked. XYZ is one of those dumb things I'd like to "just go away" though, at this point I'd even be in favor of replacing it with a tuple or vector everywhere it's used. Or preferably something more elegant.

The thing is that it's used *everywhere*, so tests passing or no I can't merge this until that use case is fixed. Can you handle that @csimal?

**Comment by csimal** [comment]
No I'm not. Those are design changes and should be your responsibility as the maintainer of this package.
If your dev environment is borked and you can't run tests either, then solving that should be your first priority.

Good luck.

**Comment by jhigginbotham64** [comment]
> Those are design changes and should be your responsibility as the maintainer of this package.

Hey, no one said community members couldn't contribute to design. Feedback is part of what I need y'all for.

If you don't want to put in the extra time or take up the additional responsibility, that's your call. Thus why I asked.

**Comment by jhigginbotham64** [comment]
> ...then solving that should be your first priority.

You don't get to tell me my priorities. Especially not while disclaiming responsibility for side effects of changes that *you* want to make.

Now I know that the CONTRIBUTING.md I'll eventually write needs to contain stipulations about contributors testings their own changes.

**Comment by csimal** [comment]
Alright then! Apologies if I sounded impolite there. What I meant was that if tests are broken (and indeed they seemed to be for me, resulting in a segfault, so the tests wouldn't even complete), then no one can actually contribute (as it turns out, I judged hastily).

I was actually able to run tests in the end. Unfortunately, the changes in this PR are indeed breaking, and fixing that would require changing large parts of the way the package works (in particular, it breaks the way the systems table in `App` uses types as keys, and fixing *that* breaks another thing, and another, ...).

I have neither the time, nor the will to get into that, and as such, will close this PR.

Sorry for the bother and good day.

**Pull request closed without merging**
